package observability

// Metadata constants migrated from certsuite identifiers.
// This file is auto-generated by cmd/migrate-identifiers.

// Descriptions
const (
	ObservabilityCompatibilityWithNextOcpReleaseDescription = `Checks to ensure if the APIs the workload uses are compatible with the next OCP version`

	ObservabilityContainerLoggingDescription = `Check that all containers under test use standard input output and standard error when logging. A container must provide APIs for the platform to observe the container health and act accordingly. These APIs include health checks (liveness and readiness), logging to stderr and stdout for log aggregation (by tools such as Logstash or Filebeat), and integrate with tracing and metrics-gathering libraries (such as Prometheus or Metricbeat).`

	ObservabilityCrdStatusDescription = `Checks that all CRDs have a status sub-resource specification (Spec.versions[].Schema.OpenAPIV3Schema.Properties[“status”]).`

	ObservabilityPodDisruptionBudgetDescription = `Checks to see if pod disruption budgets have allowed values for minAvailable and maxUnavailable, and verifies that PDBs are zone-aware (can tolerate an entire zone going offline during platform upgrades)`

	ObservabilityTerminationPolicyDescription = `Check that all containers are using terminationMessagePolicy: FallbackToLogsOnError. There are different ways a pod can stop on an OpenShift cluster. One way is that the pod can remain alive but non-functional. Another way is that the pod can crash and become non-functional. In the first case, if the administrator has implemented liveness and readiness checks, OpenShift can stop the pod and either restart it on the same node or a different node in the cluster. For the second case, when the application in the pod stops, it should exit with a code and write suitable log entries to help the administrator diagnose what the issue was that caused the problem.`

)

// Remediations
const (
	ObservabilityCompatibilityWithNextOcpReleaseRemediation = `Ensure the APIs the workload uses are compatible with the next OCP version`

	ObservabilityContainerLoggingRemediation = `Ensure containers are not redirecting stdout/stderr`

	ObservabilityCrdStatusRemediation = `Ensure that all the CRDs have a meaningful status specification (Spec.versions[].Schema.OpenAPIV3Schema.Properties[“status”]).`

	ObservabilityPodDisruptionBudgetRemediation = `Ensure minAvailable is not zero and maxUnavailable does not equal the number of pods in the replica. For multi-zone clusters, also ensure the PDB is zone-aware: set maxUnavailable >= ceil(replicas/zones) or minAvailable <= replicas - ceil(replicas/zones) to allow draining all pods in one zone during platform upgrades.`

	ObservabilityTerminationPolicyRemediation = `Ensure containers are all using FallbackToLogsOnError in terminationMessagePolicy`

)

// Best practice references
const (
	ObservabilityCompatibilityWithNextOcpReleaseBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-k8s-api-versions`

	ObservabilityContainerLoggingBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-logging`

	ObservabilityCrdStatusBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-cnf-operator-requirements`

	ObservabilityPodDisruptionBudgetBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-upgrade-expectations`

	ObservabilityTerminationPolicyBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-pod-exit-status`

)

// Exception processes
const (
	ObservabilityCompatibilityWithNextOcpReleaseExceptionProcess = `No exceptions`

	ObservabilityContainerLoggingExceptionProcess = `There is no documented exception process for this.`

	ObservabilityCrdStatusExceptionProcess = `No exceptions`

	ObservabilityPodDisruptionBudgetExceptionProcess = `No exceptions`

	ObservabilityTerminationPolicyExceptionProcess = `There is no documented exception process for this.`

)

// Impact statements
const (
	ObservabilityCompatibilityWithNextOcpReleaseImpactStatement = `Deprecated API usage can cause applications to break during OpenShift upgrades, requiring emergency fixes.`

	ObservabilityContainerLoggingImpactStatement = `Improper logging configuration prevents log aggregation and monitoring, making troubleshooting and debugging difficult.`

	ObservabilityCrdStatusImpactStatement = `Missing status subresources prevent proper monitoring and automation based on custom resource states.`

	ObservabilityPodDisruptionBudgetImpactStatement = `Improper disruption budgets can prevent necessary maintenance operations or allow too many pods to be disrupted simultaneously. Non-zone-aware PDBs can block platform upgrades when all workers in a zone need to be drained.`

	ObservabilityTerminationPolicyImpactStatement = `Incorrect termination message policies can prevent proper error reporting and make failure diagnosis difficult.`

)
