package platform

// Metadata constants migrated from certsuite identifiers.
// This file is auto-generated by cmd/migrate-identifiers.

// Descriptions
const (
	PlatformAlterationBaseImageDescription = `Ensures that the Container Base Image is not altered post-startup. This test is a heuristic, and ensures that there are no changes to the following directories: 1) /var/lib/rpm 2) /var/lib/dpkg 3) /bin 4) /sbin 5) /lib 6) /lib64 7) /usr/bin 8) /usr/sbin 9) /usr/lib 10) /usr/lib64`

	PlatformAlterationBootParamsDescription = `Tests that boot parameters are set through the MachineConfigOperator, and not set manually on the Node.`

	PlatformAlterationClusterOperatorHealthDescription = `Tests that all cluster operators are healthy.`

	PlatformAlterationHugepages1gOnlyDescription = `Check that pods using hugepages only use 1Gi size`

	PlatformAlterationHugepages2mOnlyDescription = `Check that pods using hugepages only use 2Mi size`

	PlatformAlterationHugepagesConfigDescription = `Checks to see that HugePage settings have been configured through MachineConfig, and not manually on the underlying Node. This test case applies only to Nodes that are labeled as workers with the standard label "node-role.kubernetes.io/worker". First, the MachineConfig is inspected for hugepage settings in systemd units. If not, the MC's .spec.kernelArguments are inspected for hugepage settings. The sizes and page numbers are compared, and the test passes only if they are the same than then ones in node's /sys/kernel/mm/hugepages/hugepages-X folders.`

	PlatformAlterationHyperthreadEnableDescription = `Check that baremetal workers have hyperthreading enabled`

	PlatformAlterationIsSelinuxEnforcingDescription = `verifies that all openshift platform/cluster nodes have selinux in "Enforcing" mode.`

	PlatformAlterationIsredhatReleaseDescription = `verifies if the container base image is redhat.`

	PlatformAlterationOcpLifecycleDescription = `Tests that the running OCP version is not end of life.`

	PlatformAlterationOcpNodeOsLifecycleDescription = `Tests that the nodes running in the cluster have operating systems that are compatible with the deployed version of OpenShift.`

	PlatformAlterationServiceMeshUsageDescription = `Checks if the istio namespace ("istio-system") is present. If it is present, checks that the istio sidecar is present in all pods under test.`

	PlatformAlterationSysctlConfigDescription = `Tests that no one has changed the node's sysctl configs after the node was created, the tests works by checking if the sysctl configs are consistent with the MachineConfig CR which defines how the node should be configured`

	PlatformAlterationTaintedNodeKernelDescription = `Ensures that the Node(s) hosting workloads do not utilize tainted kernels. This test case is especially
important to support Highly Available workloads, since when a workload is re-instantiated on a backup Node,
that Node's kernel may not have the same hacks.'`

)

// Remediations
const (
	PlatformAlterationBaseImageRemediation = `Ensure that Container applications do not modify the Container Base Image. In particular, ensure that the following directories are not modified: 1) /var/lib/rpm 2) /var/lib/dpkg 3) /bin 4) /sbin 5) /lib 6) /lib64 7) /usr/bin 8) /usr/sbin 9) /usr/lib 10) /usr/lib64 Ensure that all required binaries are built directly into the container image, and are not installed post startup.`

	PlatformAlterationBootParamsRemediation = `Ensure that boot parameters are set directly through the MachineConfigOperator, or indirectly through the PerformanceAddonOperator. Boot parameters should not be changed directly through the Node, as OpenShift should manage the changes for you.`

	PlatformAlterationClusterOperatorHealthRemediation = `Ensure each cluster operator is in an 'Available' state. If an operator is not in an 'Available' state, investigate the operator's logs and events to determine the cause of the failure.`

	PlatformAlterationHugepages1gOnlyRemediation = `Modify pod to consume 1Gi hugepages only`

	PlatformAlterationHugepages2mOnlyRemediation = `Modify pod to consume 2Mi hugepages only`

	PlatformAlterationHugepagesConfigRemediation = `HugePage settings for worker nodes must be configured either directly through the MachineConfigOperator or indirectly using the PerformanceAddonOperator. Avoid making changes directly to an underlying Node, and let OpenShift handle the heavy lifting of configuring advanced settings.`

	PlatformAlterationHyperthreadEnableRemediation = `Check that baremetal workers have hyperthreading enabled`

	PlatformAlterationIsSelinuxEnforcingRemediation = `Configure selinux and enable enforcing mode.`

	PlatformAlterationIsredhatReleaseRemediation = `Build a new container image that is based on UBI (Red Hat Universal Base Image).`

	PlatformAlterationOcpLifecycleRemediation = `Please update your cluster to a version that is generally available.`

	PlatformAlterationOcpNodeOsLifecycleRemediation = `Please update your workers to a version that is supported by your version of OpenShift`

	PlatformAlterationServiceMeshUsageRemediation = `Ensure all the workload pods are using service mesh if the cluster provides it.`

	PlatformAlterationSysctlConfigRemediation = `You should recreate the node or change the sysctls, recreating is recommended because there might be other unknown changes`

	PlatformAlterationTaintedNodeKernelRemediation = `Test failure indicates that the underlying Node's kernel is tainted. Ensure that you have not altered underlying Node(s) kernels in order to run the workload.`

)

// Best practice references
const (
	PlatformAlterationBaseImageBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-image-standards`

	PlatformAlterationBootParamsBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-host-os`

	PlatformAlterationClusterOperatorHealthBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-cnf-operator-requirements`

	PlatformAlterationHugepages1gOnlyBestPracticeRef = `No Doc Link - Far Edge`

	PlatformAlterationHugepages2mOnlyBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-huge-pages`

	PlatformAlterationHugepagesConfigBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-huge-pages`

	PlatformAlterationHyperthreadEnableBestPracticeRef = `No Doc Link - Extended`

	PlatformAlterationIsSelinuxEnforcingBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-pod-security`

	PlatformAlterationIsredhatReleaseBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-cnf-security`

	PlatformAlterationOcpLifecycleBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-k8s`

	PlatformAlterationOcpNodeOsLifecycleBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-host-os`

	PlatformAlterationServiceMeshUsageBestPracticeRef = `No Doc Link - Extended`

	PlatformAlterationSysctlConfigBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-cnf-security`

	PlatformAlterationTaintedNodeKernelBestPracticeRef = `https://redhat-best-practices-for-k8s.github.io/guide/#k8s-best-practices-high-level-cnf-expectations`

)

// Exception processes
const (
	PlatformAlterationBaseImageExceptionProcess = `No exceptions`

	PlatformAlterationBootParamsExceptionProcess = `No exceptions`

	PlatformAlterationClusterOperatorHealthExceptionProcess = `No exceptions`

	PlatformAlterationHugepages1gOnlyExceptionProcess = `There is no documented exception process for this.`

	PlatformAlterationHugepages2mOnlyExceptionProcess = `No exception needed for optional/extended tests.`

	PlatformAlterationHugepagesConfigExceptionProcess = `No exceptions`

	PlatformAlterationHyperthreadEnableExceptionProcess = `There is no documented exception process for this.`

	PlatformAlterationIsSelinuxEnforcingExceptionProcess = `No exceptions`

	PlatformAlterationIsredhatReleaseExceptionProcess = `No exceptions`

	PlatformAlterationOcpLifecycleExceptionProcess = `No exceptions`

	PlatformAlterationOcpNodeOsLifecycleExceptionProcess = `No exceptions`

	PlatformAlterationServiceMeshUsageExceptionProcess = `No exception needed for optional/extended tests.`

	PlatformAlterationSysctlConfigExceptionProcess = `No exceptions`

	PlatformAlterationTaintedNodeKernelExceptionProcess = `If taint is necessary, document details of the taint and why it's needed by workload or environment.`

)

// Impact statements
const (
	PlatformAlterationBaseImageImpactStatement = `Modified base images can introduce security vulnerabilities, create inconsistent behavior, and violate immutable infrastructure principles.`

	PlatformAlterationBootParamsImpactStatement = `Manual boot parameter changes bypass cluster configuration management and can cause node instability and configuration drift.`

	PlatformAlterationClusterOperatorHealthImpactStatement = `Unhealthy cluster operators can cause platform instability, feature failures, and degraded cluster functionality.`

	PlatformAlterationHugepages1gOnlyImpactStatement = `Incorrect hugepage configuration can lead to memory fragmentation and application startup failures in memory-constrained environments.`

	PlatformAlterationHugepages2mOnlyImpactStatement = `Using inappropriate hugepage sizes can cause memory allocation failures and reduce overall system performance and stability.`

	PlatformAlterationHugepagesConfigImpactStatement = `Manual hugepage configuration bypasses cluster management, can cause node instability, and creates configuration drift issues.`

	PlatformAlterationHyperthreadEnableImpactStatement = `Disabled hyperthreading reduces CPU performance and can affect workload scheduling and resource utilization efficiency.`

	PlatformAlterationIsSelinuxEnforcingImpactStatement = `Non-enforcing SELinux reduces security isolation and can allow privilege escalation attacks and unauthorized resource access.`

	PlatformAlterationIsredhatReleaseImpactStatement = `Non-Red Hat base images may lack security updates, enterprise support, and compliance certifications required for production use.`

	PlatformAlterationOcpLifecycleImpactStatement = `End-of-life OpenShift versions lack security updates and support, creating significant security and operational risks.`

	PlatformAlterationOcpNodeCountImpactStatement = `Insufficient worker nodes can prevent proper workload distribution, reduce high availability, and create resource bottlenecks.`

	PlatformAlterationOcpNodeOsLifecycleImpactStatement = `Incompatible node operating systems can cause stability issues, security vulnerabilities, and lack of vendor support.`

	PlatformAlterationServiceMeshUsageImpactStatement = `Inconsistent service mesh configuration can create security gaps, monitoring blind spots, and traffic management issues.`

	PlatformAlterationSysctlConfigImpactStatement = `Manual sysctl modifications can cause system instability, security vulnerabilities, and unpredictable kernel behavior.`

	PlatformAlterationTaintedNodeKernelImpactStatement = `Tainted kernels indicate unauthorized modifications that can introduce instability, security vulnerabilities, and support issues.`

)
